### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by hanariyada**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

**Note:** https://github.com/revoltchat/translations/issues/90 https://github.com/revoltchat/translations/issues/91

### CODE REVIEW

**Comment by Rexogamer** [comment]
This is not how maintainer requests are handled. If your maintainer request is approved, I will handle adding you to the list/giving you the relevant perms.

**Comment by hanariyada** [comment]
> This is not how maintainer requests are handled. If your maintainer request is approved, I will handle adding you to the list/giving you the relevant perms.

@Rexogamer We already have it. You can check weblate permissions.
(Pending tasks: https://github.com/revoltchat/translations/issues/90 https://github.com/revoltchat/translations/pull/272)

**Comment by Rexogamer** [comment]
You don't...? You've made contributions but your maintainer request is still pending and you don't have maintainer perms on Weblate

**Comment by hanariyada** [comment]
@Rexogamer See https://github.com/revoltchat/translations/issues/91#issuecomment-1731569314 :(
#91 (Opened date: Oct 13, 2022)

**Comment by Rexogamer** [comment]
I will review your request when I get a chance.

**Pull request closed without merging**
